### ISSUE TITLE
Equipping items that don't provide armor (elytra, carved pumpkin) with items that do (any armor set) crashes the game.

### ISSUE THREAD

**Issue by BobbyGBs** [efekos/BetterArmorHUD#1]
Version MC 1.20.2 Fabric 0.15.1
Only mods loaded are better armor hud and fabric api (and anything that comes with those)

Steps to reproduce: 
Start creative world and give either elytra or carved pumpkin as well as some armor piece
Switch to Survival 
Equip items in either order
Crash

**Comment by efekos** [comment]
Issue will be fixed in 1.0.1 version of the mod.
