### ISSUE TITLE
[BUG] Horse's health bar not visible

### ISSUE THREAD

**Issue by kkempfer** [efekos/BetterArmorHUD#2]
### Describe the bug
In Survival mode, when the player equips any piece of armor and rides a horse, the horse's health bar is not visible. Without BetterArmorHUD, the horse's health bar is always displayed. I conducted my tests on a minimal setup with only Fabric API and BetterArmorHUD installed.

### Expected behavior
The horse's health bar should always be visible.

#### Survival - Equipped only a Helmet
![2024-07-08_15 37 16](https://github.com/efekos/BetterArmorHUD/assets/43574603/5517f535-e2a5-49f1-b453-c58d0b395c6a)

#### Survival - Full Armor
![2024-07-08_15 36 46](https://github.com/efekos/BetterArmorHUD/assets/43574603/70034147-1745-48dd-beb1-ca86a6e90068)

#### Survival - No Armor
![2024-07-08_15 36 58](https://github.com/efekos/BetterArmorHUD/assets/43574603/61b06a25-1981-4668-ad84-f20c5fbd310c)

#### Creative - Equipped only a Helmet
![2024-07-08_15 37 32](https://github.com/efekos/BetterArmorHUD/assets/43574603/4a065fd9-0cfc-48a5-b096-8c7a15fcef22)

#### Survival - Equipped only a Helmet - Without BetterArmorHUD
![2024-07-08_15 41 18](https://github.com/efekos/BetterArmorHUD/assets/43574603/5cd42de9-7a3c-421f-a101-d3082048c2d0)

**Comment by efekos** [comment]
I have to investigate this issue and test if it occurs on other versions before I release an update. Use this 1.19.2 build until then. https://drive.google.com/file/d/1jFtDpEDVEzngHF0pMLxzBE2fh0UcnZoD/view

**Comment by kkempfer** [comment]
Waouw this was a quick fix ! I confirm your new version works on 1.19.2 following the same tests as described yesterday.

I am making a modpack (not published yet) featuring your mod: https://github.com/kkempfer/Create-Survive-Explore
Your new version also works with my modpack. No incompatibility to report.

I will wait for you to update the mod and publish it officially before updating it my pack, so you can benefit from the downloads through CurseForge/Modrinth.

Cheers

**Comment by efekos** [comment]
Updated version is currently out on [Modrinth](https://modrinth.com/mod/betterarmorhud/version/1.0.1+1.19.2+1), along with all other versions that had the same problem. You'll have to wait probably a few hours until CurseForge versions get approved.
